spring:
  application:
    name: index
  h2:
    console:
      path: /index/h2-console
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    # 数据库分片索引，默认为 0
    database: 0
    host: localhost
    port: 6379
    password:
  # 默认数据源
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/index/db;FILE_LOCK=FS
    username: sa
    password: sa
    # 连接池配置（默认 HikariCP）
    # 本项目要求 type 是必填的
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
# Web 容器配置
server:
  port: 9999
  address: 127.0.0.1
  tomcat:
    # 在 linux 系统中，spring boot 应用在启动的时候，会在系统的 /tmp 目录下生成一个 tomcat.* 的文件目录，
    # 上传的文件会在这个临时文件夹中保存一份，临时目录下的文件在长时间没有使用时就会被系统自动删除掉，这时候再上传文件就可能会报错，
    # 报错信息一般类似这样：The temporary upload location [/tmp/tomcat.5425935716444258807.8888/work/Tomcat/localhost/ROOT] is not
    basedir: ${user.home}/index/tmp
# 日志配置
logging:
  file: ${user.home}/index/index.log
  level:
    com.nekolr: debug
# Swagger 配置
swagger:
  basePackage: com.nekolr.index
  title: '时尚指数'
  description: '时尚指数接口服务'
  version: 0.0.1-snapshot
  host: fashion.nekolr.com
# 自定义配置
custom:
  # 自定义数据源
  datasource:
    ds1:
      # 如果没有继承配置，或者继承设置为 false，则至少需要提供 type 配置
      # 如果继承设置为 true，则可以不指定 type，除了基本配置外其他配置全部继承自默认数据源配置
      extend: true
      driver-class-name: org.h2.Driver
      url: jdbc:h2:file:~/index/db1;FILE_LOCK=FS
      username: sa
      password: sa
    ds2:
      extend: false
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: org.h2.Driver
      url: jdbc:h2:file:~/index/db2;FILE_LOCK=FS
      username: sa
      password: sa
